#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /javascript
    static_dir: javascript
    secure: always
  - url: /images
    static_dir: images
    secure: always
  - url: /stylesheets
    static_dir: stylesheets
  - url: /javascript
    static_dir: javascript
    secure: always
  - url: /.*
    script: main.app
    secure: always

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest
